const NO_URL_FOUND = 'NO_URL_FOUND';
const NO_BODY_FOUND = 'NO_BODY_FOUND';
const NO_METHOD_FOUND = 'NO_METHOD_FOUND';
const NO_HEADERS_FOUND = 'NO_HEADERS_FOUND';
const NO_MESSAGE_FOUND = 'NO_MESSAGE_FOUND';
const NO_CODE_FOUND = 'NO_CODE_FOUND';
const NO_CONSTRICT_FOUND = 'NO_CONSTRICT_FOUND';
const NO_DETAIL_FOUND = 'NO_DETAIL_FOUND';
const NO_STACK_FOUND = 'NO_STACK_FOUND';
const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
const ERROR_WHILE_PROCESSING_REQUEST = 'Error while processing the request.';

const STATUS_TEXTS = {
  400: 'Bad request parameters',
  404: 'Resource Not Found',
  500: 'Internal Server Error',
  502: 'Bad Gateway',
  503: 'Service Unavailable',
  504: 'Gateway Timeout',
};

const STATUS_CODES = {
  400: 'BAD_REQUEST',
  403: 'REQUEST_FORBIDDEN',
  404: 'NOT_FOUND',
  500: 'INTERNAL_SERVER_ERROR',
  502: 'BAD_GATEWAY',
  503: 'SERVICE_UNAVAILABLE',
  504: 'GATEWAY_TIMEOUT',
};

const REQUEST_VALIDATION_ERROR = 'REQUEST_VALIDATION_ERROR';

export {
  ERROR_WHILE_PROCESSING_REQUEST,
  INTERNAL_SERVER_ERROR,
  NO_BODY_FOUND,
  NO_CODE_FOUND,
  NO_CONSTRICT_FOUND,
  NO_DETAIL_FOUND,
  NO_HEADERS_FOUND,
  NO_MESSAGE_FOUND,
  NO_METHOD_FOUND,
  NO_STACK_FOUND,
  NO_URL_FOUND,
  REQUEST_VALIDATION_ERROR,
  STATUS_CODES,
  STATUS_TEXTS,
};
